name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.tool-versions'
      - run: bun install --frozen-lockfile
      - run: bun run format
      - run: bun run build
